### ISSUE TITLE
Problem to compile with QtCreator

### ISSUE THREAD

**Issue by nancho81** [dimkanovikov/WebLoader#12]
[WebloaderErrors.log](https://github.com/dimkanovikov/WebLoader/files/4011688/WebloaderErrors.log)

I try to compile with Qt Creator (Qt 5.9.9) and gave me several errors (attached in WebloaderErrors.log). Some of these errors are the similar but I couldn't find the way to solve this.

Thanks in advance.
Hernan

**Comment by dimkanovikov** [comment]
Did you try to compile example application from the repo or your own? Looks like you try to compile with qt4...

**Comment by nancho81** [comment]
Thanks!!!! I found two manual Qt4 definitions and I think Qt Creator must be using one of this versions. Even when I choose a Qt5 version by default. I remove these Qt4 version and I could compile it.
