### ISSUE TITLE
How to set or handle timeout related things?

### ISSUE THREAD

**Issue by xeoshow** [dimkanovikov/WebLoader#2]
Hi,

Just found this neat and lightweight lib for qt, and just would like to know how to set or handle timeout related things?

For example, regarding below code, if github.com is down, how long it will wait and how about the result of data? 
const QByteArray data = NetworkRequestLoader::loadSync("https://github.com");

Thanks!

**Comment by dimkanovikov** [comment]
Hello,

You can configure timeout related things with NetworkRequest instance via _NetworkRequest::setLoadingTimeout_ and _NetworkRequest::getLoadingTimeout_.

If github.com will be down lib will be wait 20000 milliseconds by default and then will return empty result. But if you use NetworkRequest instance, you can get error information from _NetworkRequest::error_ signal.

**Comment by xeoshow** [comment]
Thanks so much for quick and helpful reply!

**Comment by dimkanovikov** [comment]
You are welcome!
