### ISSUE TITLE
Got error when build regarding TooManyRedirectsError and InsecureRedirectError..

### ISSUE THREAD

**Issue by xeoshow** [dimkanovikov/WebLoader#3]
Hello,

I used Qt 5.5.1, and import the project, when compiling, got below error. How could I fix this? Thanks!

D:\gitrepository\WebLoader-master\src\WebLoader_p.cpp:75: error: 'TooManyRedirectsError' is not a member of 'QNetworkReply'
    case QNetworkReply::TooManyRedirectsError: result = "while following redirects, the maximum limit was reached. The limit is by default set to 50 or as set by QNetworkRequest::setMaxRedirectsAllowed()."; break;
         ^

D:\gitrepository\WebLoader-master\src\WebLoader_p.cpp:76: error: 'InsecureRedirectError' is not a member of 'QNetworkReply'
    case QNetworkReply::InsecureRedirectError: result = "while following redirects, the network access API detected a redirect from a encrypted protocol (https) to an unencrypted one (http)."; break;
         ^

**Comment by dimkanovikov** [comment]
Fixed. Try to load new changes and rebuild now.

**Comment by xeoshow** [comment]
no error now and compiled correctly! Thank you!
