### ISSUE TITLE
How could I use WebLoader to download image file or zip file?

### ISSUE THREAD

**Issue by xeoshow** [dimkanovikov/WebLoader#7]
Hi,
    WebLoader is really good, and now I met an issue that how could I use WebLoader to download image file or zip file? Thanks!

**Comment by dimkanovikov** [comment]
Hi, xeoshow!

Just load image or zip file from their link (for example https://www.wikipedia.org/portal/wikipedia.org/assets/img/Wikipedia-logo-v2.png) and than save loaded data to file.

I really don't understand in what is actually trouble?

**Comment by xeoshow** [comment]
Hi, 

YES, I found it works directly! And my code problem, now works great! A small suggestion: add some description to WebLoader GIT home page, so readers are aware of this feature.

Thanks again!

**Comment by dimkanovikov** [comment]
Thanks!
