### ISSUE TITLE
How could I upload file to server side via WebLoader?

### ISSUE THREAD

**Issue by xeoshow** [dimkanovikov/WebLoader#9]
Hello, 

I have some local log files, which would need send to server side, how should I do this via WebLoader?

Thanks a lot!

Best regards, Jason

**Comment by dimkanovikov** [comment]
Hey, Jason.

You should place to server side script which will save files on the server and after that, you can send your files to them like this:

```
NetworkRequest loader;
loader.setRequestMethod(NetworkRequest::Post);
loader.addRequestAttributeFile("file", filePath);
loader.loadSync("https://yoursite.com/savefile/");
```

**Comment by xeoshow** [comment]
Thanks for help!

So, I could also use loadAsync instead of the loadSync regarding the last code line?

Best regards, Jason

**Comment by dimkanovikov** [comment]
It depends on your needs if you want you can use loadAsync of course.
